export const TEST = "TEST";

export const LOGIN_LOADING = "LOGIN_LOADING";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";

export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGGED_IN_STATE = "LOGGED_IN_STATE";
export const LOGOUT_SUCCESS = "LOGOUT";

export const GET_ALL_PLAYERS_LOADING = "GET_ALL_PLAYERS_LOADING";
export const GET_ALL_PLAYERS_SUCCESS = "GET_ALL_PLAYERS_SUCCESS";

export const POST_TEAM_LOADING = "POST_TEAM_LOADING";
export const POST_TEAM_FAILED = "POST_TEAM_FAILED";
export const POST_TEAM_SUCCESS = "POST_TEAM_SUCCESS";
